[project]
name = "02-pandas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ShahJabir", email = "shahjabirofficial@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "pandas>=3.0.6",
]

[project.scripts]
02-pandas = "02_pandas:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
