[project]
name = "01-numpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ShahJabir", email = "shahjabirofficial@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
]

[project.scripts]
01-numpy = "01_numpy:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
